"""empty message

Revision ID: 1bcc22d09809
Revises: 5bd4d3ed18ea
Create Date: 2022-08-10 16:27:53.584630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcc22d09809'
down_revision = '5bd4d3ed18ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('cod_dpto', sa.Integer(), nullable=False),
    sa.Column('nome_dpto', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cod_dpto')
    )
    op.create_table('disciplinas',
    sa.Column('cod_disc', sa.Integer(), nullable=False),
    sa.Column('nome_disc', sa.String(length=50), nullable=False),
    sa.Column('carga_horaria', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cod_disc')
    )
    op.create_table('cursos',
    sa.Column('cod_curso', sa.Integer(), nullable=False),
    sa.Column('nome_curso', sa.String(length=50), nullable=False),
    sa.Column('cod_dpto', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_dpto'], ['departamentos.cod_dpto'], ),
    sa.PrimaryKeyConstraint('cod_curso')
    )
    op.create_table('alunos',
    sa.Column('mat_alu', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('cotista', sa.Boolean(), nullable=True),
    sa.Column('cod_curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_curso'], ['cursos.cod_curso'], ),
    sa.PrimaryKeyConstraint('mat_alu')
    )
    op.create_table('matrizes_cursos',
    sa.Column('cod_curso', sa.Integer(), nullable=True),
    sa.Column('cod_disc', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_curso'], ['cursos.cod_curso'], ),
    sa.ForeignKeyConstraint(['cod_disc'], ['disciplinas.cod_disc'], )
    )
    op.create_table('matriculas',
    sa.Column('id_matriculas', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('mat_alu', sa.Integer(), nullable=False),
    sa.Column('cod_disc', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('faltas', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['cod_disc'], ['disciplinas.cod_disc'], ),
    sa.ForeignKeyConstraint(['mat_alu'], ['alunos.mat_alu'], ),
    sa.PrimaryKeyConstraint('id_matriculas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matriculas')
    op.drop_table('matrizes_cursos')
    op.drop_table('alunos')
    op.drop_table('cursos')
    op.drop_table('disciplinas')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
