"""empty message

Revision ID: 5bd4d3ed18ea
Revises: 51762fe8512f
Create Date: 2022-08-09 22:09:50.239404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd4d3ed18ea'
down_revision = '51762fe8512f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('periodo', sa.Integer(), nullable=False))
    op.add_column('matrizes_cursos', sa.Column('periodo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrizes_cursos', 'periodo')
    op.drop_column('cursos', 'periodo')
    # ### end Alembic commands ###
