"""empty message

Revision ID: 856d0fcc316e
Revises: 
Create Date: 2022-08-02 14:22:53.003531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856d0fcc316e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('publisher_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('publisher_estd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publsiher_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publsiher_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('publisher_id', name='publisher_pkey')
    )
    op.create_table('vendas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('funcionario', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vendas', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('dia_semana', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vendas_pkey')
    )
    # ### end Alembic commands ###
