"""empty message

Revision ID: 8b56241fdf03
Revises: 5b2419770157
Create Date: 2022-08-03 19:41:51.385156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b56241fdf03'
down_revision = '5b2419770157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('developers', 'accepted_remote_work',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'developers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'developers', type_='foreignkey')
    op.alter_column('developers', 'accepted_remote_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('developers', 'user_id')
    # ### end Alembic commands ###
